name: Build

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  arm64:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.79
          targets: aarch64-unknown-linux-musl

      - name: Install musl-tools
        run: sudo apt-get update && sudo apt-get install -y musl-tools

      - name: Build for aarch64
        run: cargo build --release --package forwarder-cli --target aarch64-unknown-linux-musl

      - name: Prepare binary
        run: |
          mkdir -p dist
          cp target/x86_64-unknown-linux-musl/release/forwarder-cli dist/wg-forwarder-amd64
          chmod +x dist/wg-forwarder-amd64

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: wg-forwarder-amd64
          path: dist/wg-forwarder-amd64

  amd64:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.79
          targets: x86_64-unknown-linux-musl

      - name: Install musl-tools
        run: sudo apt-get update && sudo apt-get install -y musl-tools

      - name: Build for x86_64
        run: cargo build --release --package forwarder-cli --target x86_64-unknown-linux-musl

      - name: Prepare binary
        run: |
          mkdir -p dist
          cp target/x86_64-unknown-linux-musl/release/forwarder-cli dist/wg-forwarder-amd64
          chmod +x dist/wg-forwarder-amd64

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: wg-forwarder-amd64
          path: dist/wg-forwarder-amd64

  release:
    runs-on: ubuntu-latest
    needs: [amd64, arm64]

    steps:
      - name: Download amd64 binary
        uses: actions/download-artifact@v3
        with:
          name: wg-forwarder-amd64
          path: dist

      - name: Download arm64 binary
        uses: actions/download-artifact@v3
        with:
          name: wg-forwarder-arm64
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/wg-forwarder-amd64
            dist/wg-forwarder-arm64
