name: Build

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install cross
        run: cargo install cross

      - name: Build with cross
        run: |
          cross build --release --target x86_64-unknown-linux-musl --package forwarder-cli
          cross build --release --target aarch64-unknown-linux-musl --package forwarder-cli
          mkdir -p dist
          cp target/x86_64-unknown-linux-musl/release/forwarder-cli dist/wg-forwarder-amd64
          cp target/aarch64-unknown-linux-musl/release/forwarder-cli dist/wg-forwarder-arm64
          chmod +x dist/*

      - name: Release binaries
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/wg-forwarder-amd64
            dist/wg-forwarder-arm64
