name: Build

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install cross
        run: cargo install cross

      - name: Build for x86_64
        run: cross build --release --target x86_64-unknown-linux-musl --package forwarder-cli

      - name: Prepare binaries
        run: |
          mkdir -p dist
          cp target/x86_64-unknown-linux-musl/release/forwarder-cli dist/wg-forwarder-amd64
          cp target/aarch64-unknown-linux-musl/release/forwarder-cli dist/wg-forwarder-arm64
          chmod +x dist/*

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/wg-forwarder-amd64
